### ISSUE TITLE
Issue in read all / read by where clause in indexed field

### ISSUE THREAD

**Issue by heckdevice** [Wiredcraft/loopback-connector-couchbase3#45]
I get the following error evertime i do a get all for a Model instances.

Also the get by Id or where clause based fetch gets zero results (with no error)

The below error comes only in case of getAll APIs

Unhandled rejection Error: ...
    at Couchbase.all (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-connector-couchbase3/lib/couchbase3.js:317:27)
    at /Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/dao.js:1773:19
    at doNotify (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at doNotify (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at doNotify (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at doNotify (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:121:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:119:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:119:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/shpant/Desktop/laptopBackup/Shared-Desktop/src/stash/sls/node_modules/ski/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)

---

Node v4.4.3
"dependencies": {
    "body-parser": "^1.15.0",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "couchbase": "^2.1.7",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-couchbase3": "^0.2.2",
    "loopback-connector-mongodb": "^1.13.3",
    "loopback-datasource-juggler": "^2.46.1",
    "node-uuid": "^1.4.7",
    "serve-favicon": "^2.0.1"
  }

Mode.json

{
  "name": "keyword",
  "plural": "keywords",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "userid": {
      "type": "string",
      "required": true,
      "index":true,
      "unique":true
    },
    "userprofile": {
      "type": "string",
      "required": true,
      "index":true,
      "unique":true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

**Comment by makara** [comment]
Thanks and sorry the get all instances is not implemented. I'm planning to push it with a new release within a week.

**Comment by makara** [comment]
Done long ago. Closing.
